# default: &default
#   adapter: postgresql
#   encoding: unicode
#   # For details on connection pooling, see Rails configuration guide
#   # https://guides.rubyonrails.org/configuring.html#database-pooling
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: limco_carwash_development

# test:
#   <<: *default
#   database: limco_carwash_test

# production:
#   <<: *default
#   database: limco_carwash_production
#   username: limco_carwash
#   password: <%= ENV["LIMCO_CARWASH_DATABASE_PASSWORD"] %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: limco_carwash_development

test:
  <<: *default
  database: limco_carwash_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  pool: 5
  timeout: 5000
